# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 416ea2b8c54447da39c1ac1c2d0b6e29b21b9855b469d44bf49fc96524491642996a3f2d0fa9a5ff5466c4da0508264a497b44e68f199b526046c46e9318e739

test:
  secret_key_base: dfd0c79cca96c1c1f99a5603177a3f655820faee06ff21a91b7e9b9db277fb383dd645338d9fc82ee4a92ccc63084c3975afc6e23efce50fb2d71fca3c013811

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
